food/urls.py
from django.conf.urls import url

from .views import index,add_meal,delete_meal,update_meal,view_meal

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_meal$', add_meal, name='add-meal'),
    url(r'^delete_meal/(?P<meal_id>\d+)$', delete_meal, name='delete-meal'),
    url(r'^update_meal/(?P<meal_id>\d+)$', update_meal, name='update-meal'),
    url(r'^view_meal/(?P<meal_id>\d+)$', view_meal, name='view-meal'),
]

food_tracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('food.urls', 'food'), namespace="food")),
]

food/models.py
from django.db import models

class Food(models.Model):
	name = models.CharField(verbose_name="Name", max_length=128)
	calories = models.FloatField(verbose_name="Calories (kcal)")
	total_fat = models.FloatField(verbose_name="Total Fat (g)")
	saturated_fat = models.FloatField(verbose_name="Saturated Fat (g)")
	cholesterol = models.FloatField(verbose_name="Cholesterol (mg)")
	sodium = models.FloatField(verbose_name="Sodium (mg)")
	total_carbohydrate = models.FloatField(verbose_name="Total Carbohydrate (g)")
	dietary_fibre = models.FloatField(verbose_name="Dietary Fibre (g)")
	sugar = models.FloatField(verbose_name="Sugar (g)")
	protein = models.FloatField(verbose_name="Protein (g)")

	def __str__(self):
		return "%s" % self.name

class Meal(models.Model):
	BREAKFAST = 1
	MORNING_SNACK = 2
	LUNCH = 3
	AFTERNOON_SNACK = 4
	DINNER = 5
	EVENING_SNACK = 6

	MEAL_TIME_TYPES = (
		(BREAKFAST, "Breakfast"),
		(MORNING_SNACK, "Morning Snack"),
		(LUNCH, "Lunch"),
		(AFTERNOON_SNACK, "Afternoon Snack"),
		(DINNER, "Dinner"),
		(EVENING_SNACK, "Evening Snack")
	)

	food = models.ForeignKey(Food, verbose_name="Food" , on_delete = models.CASCADE)
	serving_size = models.IntegerField(verbose_name="Serving Size")
	meal_time = models.IntegerField(verbose_name="Meal Time", choices=MEAL_TIME_TYPES)
	
	def get_total_calories(self):
		return self.serving_size * self.food.calories

	def __str__(self):
		return "%s" % self.food

	def get_total_fat(self):
		return self.serving_size * self.food.total_fat

	def get_total_saturated_fat(self):
		return self.serving_size * self.food.saturated_fat

	def get_total_cholesterol(self):
		return self.serving_size * self.food.cholesterol

	def get_total_sodium(self):
		return self.serving_size * self.food.sodium

	def get_total_carbohydrate(self):
		return self.serving_size * self.food.total_carbohydrate

	def get_total_dietary_fibre (self):
		return self.serving_size * self.food.dietary_fibre 

	def get_total_sugar(self):
		return self.serving_size * self.food.sugar

	def get_total_protein(self):
		return self.serving_size * self.food.protein

food/forms.py
from django import forms
from .models import Meal

class MealForm(forms.ModelForm):
	class Meta:
		model = Meal
		fields = "__all__"

food/views.py
from django.shortcuts import render
from .models import Food, Meal
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .forms import MealForm


def index(request):
	template = 'list.html'
	meals = Meal.objects.all()
	context = {
         'meals': meals,
    }
	return render(request, template, context)

def add_meal(request):
	template = "add_meal.html"

	if request.method == "POST":
		form = MealForm(request.POST)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		context = {
			'meal_form': MealForm(),
		}
		return render(request, template, context)

def delete_meal(request, meal_id):
	meal = Meal.objects.get(id=int(meal_id))
	meal.delete()
	return HttpResponseRedirect(reverse_lazy('food:index'))

def update_meal(request, meal_id):
	template = "update_meal.html"
	meal = Meal.objects.get(id=int(meal_id))

	if request.method == "POST":
		form = MealForm(request.POST, instance=meal)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse_lazy('food:index'))
	else:
		context = {
			'meal_form': MealForm(instance=meal),
		}
		return render(request, template, context)

def view_meal(request, meal_id):
	template = "view_meal.html"
	meal = Meal.objects.get(id=int(meal_id))
	context = {
		'meal': meal,
	}

	return render(request, template, context)

templates/add_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Add Meal</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Food</th>
						<th>{{ meal_form.food }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal_form.serving_size }}</th>
					</tr>
					<tr>
						<th>Meal Time</th>
						<th>{{ meal_form.meal_time }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
	</body>
</html>

templates/index.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker</h1>
		<a href="{% url 'auth_logout' %}">Logout</a> <br /><br />

		<a href="{% url 'auth_password_change' %}">Change Password</a> <br /><br />

		<a href="{% url 'food:add-meal' %}" class="btn btn-success">Add Meal</a> <br /> <br />

		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>Food</th>
					<th>Meal Time</th>
					<th>Calories</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for meal in meals %}
				<tr>
					<td>{{ meal.food }}</td>
					<td>{{ meal.get_meal_time_display }}</td>
					<td>{{ meal.get_calories }}</td>
					<td>
						<a href="" class="btn btn-info">View</a> 
					</td>
					<td>
						<a href="{% url 'food:update-meal' meal.id %}" class="btn btn-primary">Update</a> 
					</td>
					<td>
						<a href="{% url 'food:delete-meal' meal.id %}" class="btn btn-danger">Delete</a> 
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan="6">No meals yet</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

templates/list.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker</h1> <br /><br />


		<a href="{% url 'food:add-meal' %}" class="btn btn-success">Add Meal</a> <br /><br />

		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Food</th>
					<th>Meal Time</th>
					<th>Total Calories</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for meal in meals %}
				<tr>
					<td>{{ meal.food.name }}</td>
					<td>{{ meal.get_meal_time_display }}</td>
					<td>{{ meal.get_total_calories }} kcal</td>
					<td>
						<a href="{% url 'food:view-meal' meal.id %}" class="btn btn-info">View</a>
					</td>
					<td>
						<a href="{% url 'food:update-meal' meal.id %}" class="btn btn-primary">Update</a>
					</td>
					<td>
						<a href="{% url 'food:delete-meal' meal.id %}" class="btn btn-danger">Delete</a>
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan=6>No meals yet</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

templates/login.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        <style type="text/css">
            html,
            body {
                height: 100%;
            }

            body {
                padding-top: 40px;
                padding-bottom: 40px;
            }

            .form-signin {
                width: 100%;
                max-width: 330px;
                padding: 15px;
                margin: auto;
            }
        </style>

    </head>

    <body class="text-center">
        <form class="form-signin" method="POST" action="{% url 'auth_login' %}" role="form">
            {% csrf_token %}

            <h1>My Food Tracker</h1>

            {{ form.username.label }}
            {{ form.username }}

            {{ form.password.label }}
            {{ form.password }}

            <button class="btn btn-lg btn-primary" type="submit">Sign in</button>
            <input type="hidden" name="next" value="{% url 'food:index' %}" />
        </form>
    </body>
</html>

templates/password_change.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker</h1>
		<a href="{% url 'auth_logout' %}">Logout</a> <br /><br />

		{{ form.errors }}

		<form method="POST" action="{% url 'auth_password_change' %}">
		    {% csrf_token %}

		    {{ form.old_password.label }}
		    {{ form.old_password }} <br /><br />

		    {{ form.new_password1.label }}
		    {{ form.new_password1 }} <br /><br />
		    
		    {{ form.new_password2.label }}
		    {{ form.new_password2 }} <br /><br />

		    <button type="submit" class="btn btn-success">Change password</button>
		</form>
	</body>
</html>

templates/update_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
		<h1>My Food Tracker - Update Meal</h1>
		<form role="form" action="" method="POST">
		    {% csrf_token %}
			<table class="table table-bordered table-striped">
				<tbody>
					<tr>
						<th>Food</th>
						<th>{{ meal_form.food }}</th>
					</tr>
					<tr>
						<th>Serving Size</th>
						<th>{{ meal_form.serving_size }}</th>
					</tr>
					<tr>
						<th>Meal Time</th>
						<th>{{ meal_form.meal_time }}</th>
					</tr>
				</tbody>
			</table>
			<button type="submit" class="btn btn-success">Save</button>
		</form>
	</body>
</html>

templates/view_meal.html
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	</head>
	<body>
		<div class="container">
			<div class="bg-success">
				<h1 style="padding-top: 26px; color: #ffffff;">View Meal Details</h1> <br /><br />
			</div>

			<h3>{{ meal.food.name }}</h3><br/>

			<table class="table table-striped table-bordered">
				<tbody>
					{% if meal %}
					<tr>
						<th>Calories</th>
						<td>{{ meal.get_total_calories }} kcal</td>
					</tr>
					<tr>
						<th>Serving Size</th>
						<td>{{ meal.serving_size }}</td>
					</tr>
					<tr>
						<th>Total Fat</th>
						<td>{{ meal.get_total_fat }} g</td>
					</tr>
					<tr>
						<th>Saturated Fat</th>
						<td>{{ meal.get_total_saturated_fat }} g</td>
					</tr>
					<tr>
						<th>Cholesterol</th>
						<td>{{ meal.get_total_cholesterol }} mg</td>
					</tr>
					<tr>
						<th>Sodium</th>
						<td>{{ meal.get_total_sodium }} mg</td>
					</tr>
					<tr>
						<th>Total Carbohydrate</th>
						<td>{{ meal.get_total_carbohydrate }} g</td>
					</tr>
					<tr>
						<th>Dietary Fibre</th>
						<td>{{ meal.get_total_dietary_fibre }} g</td>
					</tr>
					<tr>
						<th>Sugar</th>
						<td>{{ meal.get_total_sugar }} g</td>
					</tr>
					<tr>
						<th>Protein</th>
						<td>{{ meal.get_total_protein }} g</td>
					</tr>
					{% else %}
					<tr>
						<td colspan=2>No meals yet</td>
					</tr>
					{% endif %}
				</tbody>
			</table>
		</div>
	</body>
</html>